# Generated by Django 4.2.9 on 2024-09-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional_salud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesionalsalud',
            old_name='especilidad',
            new_name='especialidad',
        ),
        migrations.AddField(
            model_name='profesionalsalud',
            name='dni',
            field=models.CharField(default=454545, max_length=8),
            preserve_default=False,
        ),
    ]
