# Generated by Django 4.2.9 on 2024-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional_salud', '0002_rename_especilidad_profesionalsalud_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionalsalud',
            name='dni',
        ),
        migrations.AddField(
            model_name='profesionalsalud',
            name='llave_publica',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profesionalsalud',
            name='matricula',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
