# Generated by Django 4.2.9 on 2024-08-17 21:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_informe', models.DateField()),
                ('archivo', django_cryptography.fields.encrypt(models.BinaryField(editable=True))),
            ],
        ),
    ]
