# Generated by Django 5.0.6 on 2024-06-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('profesional_salud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesional_salud.profesional_salud')),
            ],
        ),
    ]
