# Generated by Django 4.2.9 on 2024-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_informe', models.DateField()),
                ('archivo', models.BinaryField(editable=True)),
                ('llave_simetrica_encriptada', models.BinaryField()),
            ],
        ),
    ]
