# Generated by Django 4.2.9 on 2024-09-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('informe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
