# Generated by Django 4.2.9 on 2024-08-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informe', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
