# Generated by Django 5.0.6 on 2024-07-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informe', '0002_initial'),
        ('profesional_salud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='profesional_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesional_salud.profesional_salud'),
        ),
    ]
