# Generated by Django 5.0.6 on 2024-07-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='archivo',
            field=models.BinaryField(editable=True),
        ),
    ]
