# Generated by Django 4.2.9 on 2024-10-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesional_salud', '0001_initial'),
        ('paciente', '0001_initial'),
        ('informe', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_informe', models.DateField()),
                ('archivo', models.BinaryField(editable=True)),
                ('llave_simetrica_encriptada', models.BinaryField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('profesional_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesional_salud.profesionalsalud')),
            ],
        ),
    ]
