# Generated by Django 5.0.6 on 2024-07-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0004_alter_informe_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='titulo',
            field=models.CharField(default='titulo prueba', max_length=200),
            preserve_default=False,
        ),
    ]
