# Generated by Django 4.2.9 on 2024-10-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0006_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_de_vida',
            field=models.IntegerField(null=True),
        ),
    ]
