# Generated by Django 5.0.6 on 2024-07-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('turno_profesional_salud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guia_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('turno_profesional_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turno_profesional_salud.turno_profesional_salud')),
            ],
        ),
    ]
