# Generated by Django 5.0.6 on 2024-07-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia_paciente', '0002_initial'),
        ('turno_profesional_salud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia_paciente',
            name='turno_profesional_salud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turno_profesional_salud.turno_profesional_salud'),
        ),
    ]
