# Generated by Django 5.0.6 on 2024-06-05 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informe', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informe.informe')),
                ('pociente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
