# Generated by Django 5.0.6 on 2024-07-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial_medico', '0001_initial'),
        ('informe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_medico',
            name='informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informe.informe'),
        ),
    ]
